---

# RedHat
- include: rhel/default.yml
  when: ansible_os_family == "RedHat"
  tags: autologic_osupdate_play_redhat

- include: rhel/disabled_repositories.yml
  when: ansible_os_family == "RedHat"
  tags: autologic_osupdate_play_redhat_exclusions

- include: rhel/enabled_repositories.yml
  when: ansible_os_family == "RedHat"
  tags: autologic_osupdate_play_redhat_inclusions

- include: rhel/exclude_include_repositories.yml
  when: ansible_os_family == "RedHat"
  tags: autologic_osupdate_play_redhat_include_exclude

# FreeBSD
- include: freebsd/default.yml
  when: ansible_os_family == "FreeBSD"
  tags: autologic_osupdate_play_freebsd
