---

- include: rhel.yml
  when: ansible_os_family == "RedHat"
  tags:
    - autologic_osupdate_play_redhat

- include: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - autologic_osupdate_play_debian

- include: reboot.yml
  when: autologic_osupdate_reboot_system
  tags:
    - autologic_osupdate_play_reboot
