---

- name: Setup system repositories
  template:
    src: 'yum-repository.j2'
    dest: "/etc/yum.repos.d/autologic-packages.repo"
    mode: 0600
    owner: 'root'
    group: 'root'

- name: Install repository RPMs
  yum:
    name: "{{item.rpm}}"
    state: 'present'
  with_items: autologic_software_repositories
  when: '"rpm" in item'
