# Author: Michael Crilly
# Copyright (C) 2015 AutoLogic Technology Ltd
# Licence: MIT 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "movedx/centos-6.6"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |p|
    p.memory = 256
    p.cpus = 1
  end

  config.vm.define "autologic-packages"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
  end
end
