---

- name: Update the OS base packages (RedHat)
  yum:
    name: "{{autologic_osupdate_packages}}"
    state: "{{autologic_osupdate_packages_state}}"
    disable_gpg_check: "{{autologic_osupdate_no_gpg_checks}}"
  ignore_errors: autologic_osupdate_ignore_errors
  tags: autologic_osupdate_task_update
  when: not autologic_osupdate_enabled_repositories and not autologic_osupdate_disabled_repositories
